In [7]:
import numpy as np

In [8]:
a=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:

b=a.T

print (b)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
